(load "request.lisp")
(load "packages.lisp")
(in-package :web-cl)
(load "utils.lisp")
(load "mime.lisp")
(load "handlers.lisp")
(load "dispatch.lisp")
(setf *mime-table* (make-hash-table))
(init-mime-table mime-table *mime-table*)
(start-web)